import "./globals.css";
import ParticlesComponent from "../components/Particles";
import { Inter } from "next/font/google";
import Bar from "@/components/Bar";
import Footer from "@/components/Footer";
import { Suspense } from "react";
import Loading from "./loading";
import { Toaster } from 'sonner';

const font = Inter({ subsets: ["latin"], weight: "600" });

export const metadata = {
  title: "Ariel Martinez | Portfolio 2024",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={font.className}>
      <Suspense fallback={<Loading />}>
        <ParticlesComponent id="particles" />
        <Bar />
        {children}
        <Toaster />
        <Footer />
        </Suspense>
      </body>
    </html>
  );
}
